"""init db

Revision ID: 0b74b8905b04
Revises: 
Create Date: 2021-10-24 15:38:11.007594

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0b74b8905b04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'faculties',
        sa.Column('faculty_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('faculty_id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'teachers',
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('teacher_id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'users',
        sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_table(
        'groups',
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('course', sa.Integer(), nullable=False),
        sa.Column('studying_years', sa.String(length=10), nullable=False),
        sa.Column('faculty_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['faculty_id'], ['faculties.faculty_id'], onupdate='CASCADE',
                                ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table(
        'day_schedule',
        sa.Column('day_schedule_id', sa.Integer(), nullable=False),
        sa.Column('day_of_week',
                  sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
                          name='weekday'), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('day_schedule_id')
    )
    op.create_table(
        'user_groups',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table(
        'subjects',
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('subject_name', sa.String(length=100), nullable=False),
        sa.Column('lesson_type', sa.Enum('lecture', 'practice', name='lessontype'), nullable=False),
        sa.Column('lesson_slot', sa.Integer(), nullable=False),
        sa.Column('lesson_slot_duration', sa.String(length=15), nullable=False),
        sa.Column('lesson_dates', postgresql.ARRAY(sa.Date()), nullable=False),
        sa.Column('day_schedule_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['day_schedule_id'], ['day_schedule.day_schedule_id'], onupdate='CASCADE',
                                ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table(
        'subject_groups',
        sa.Column('subject_group_id', sa.Integer(), nullable=False),
        sa.Column('classroom', sa.Integer(), nullable=False),
        sa.Column('group_name', sa.String(length=20), nullable=True),
        sa.Column('subject_id', sa.Integer(), nullable=True),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], onupdate='CASCADE',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], onupdate='CASCADE',
                                ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('subject_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_groups')
    op.drop_table('subjects')
    op.drop_table('user_groups')
    op.drop_table('day_schedule')
    op.drop_table('groups')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('faculties')
    # ### end Alembic commands ###
