"""changed user_groups to user_lessons

Revision ID: 3f959419275c
Revises: b59c5365298d
Create Date: 2022-03-16 11:30:27.556530

"""
#  Copyright (c) 2022 Vladyslav Synytsyn.

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3f959419275c'
down_revision = 'b59c5365298d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lessons',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'lesson_id')
                    )
    op.drop_table('user_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name='user_groups_group_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_groups_user_id_fkey'),
                    sa.PrimaryKeyConstraint('user_id', 'group_id', name='user_groups_pkey')
                    )
    op.drop_table('user_lessons')
    # ### end Alembic commands ###
