"""added semester to group

Revision ID: 84127ee44a89
Revises: 0b74b8905b04
Create Date: 2021-10-25 00:20:41.384807

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '84127ee44a89'
down_revision = '0b74b8905b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('semester', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('groups', 'semester')
    # ### end Alembic commands ###
